set_property IOSTANDARD LVCMOS33 [get_ports {recive_datas[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {recive_datas[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {recive_datas[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {recive_datas[1]}]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN M15 [get_ports rst]
set_property PACKAGE_PIN J14 [get_ports {recive_datas[0]}]
set_property PACKAGE_PIN J18 [get_ports {recive_datas[2]}]
set_property PACKAGE_PIN K14 [get_ports {recive_datas[1]}]
set_property PACKAGE_PIN H18 [get_ports {recive_datas[3]}]

create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
